// eslint-disable-next-line @typescript-eslint/no-require-imports
const fs = require('fs');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const path = require('path');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { cosmiconfigSync } = require('cosmiconfig');
const explorer = cosmiconfigSync('tailsafe');
const userConfigResult = explorer.search();
const userConfig = userConfigResult ? userConfigResult.config : {};
const aliases = userConfig.aliases || {};

if (!userConfigResult) {
  // eslint-disable-next-line no-console
  console.warn('⚠️  No tailSafe.config.ts found');
  process.exit(1);
}

// 1. Generate TypeScript module augmentation
const lines = [];
for (const alias of Object.keys(aliases)) {
  lines.push(`    ${alias}?: string | string[] | boolean;`);
}

const output = `// AUTO-GENERATED FILE. DO NOT EDIT.\n// Generated by tailSafe 🦈
import 'tailsafe';

declare module 'tailsafe' {
  interface TailSafe {
    ${lines.join('\n    ')}
  }
}
`;

// Write to .tailSafe/tailSafe.aliases.d.ts in the user's project root
const userRoot = process.cwd();
const outDir = path.join(userRoot, '.tailsafe');
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}
const outFile = path.join(outDir, 'tailSafe.aliases.d.ts');
fs.writeFileSync(outFile, output);